name: "validate gradle wrapper"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
      - name: "validate gradle wrapper"
        uses: "gradle/wrapper-validation-action@v1"
